[build]
  command = "npm run build"
  publish = "dist"
  base = "."

[build.environment]
  NODE_VERSION = "18.17.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist"